data_ingestion_config:
  dataset_download_file_name: adult.csv
  dataset_download_id: https://raw.githubusercontent.com/ARPITA-ds/ml_pipeline_project/main/cleandata.csv
  ingested_dir: ingested_data
  ingested_test_file: test.csv
  ingested_train_file: train.csv
  ingestion_dir: Stage00_data_ingestion
  raw_data_dir: raw_data

training_pipeline_config:
  artifact_dir: artifact
  experiment_code: Development
  pipeline_name: mlpipeline


data_transformation_config:
  data_transformation_dir: stage03_data_transformation
  preprocessing_object_dir: preprocessing
  preprocessing_object_file_name: preprocessing_obj.pkl


model_trainer_config:
  model_reports_dir: model_eval_reports
  model_trainer_dir: stage04_model_training
 